### PR TITLE
D8UN-185-file-bug

### PR DESCRIPTION
**Pull request by soda736**
Changing attachment field to entity reference

### CODE REVIEW

**Review by omahm — APPROVED** [review]
LGTM

**Comment by DuttonMa** [comment]
As discussed, think we should just hold on to this change for now. It may be necessary to do this, but it would be better if we didn't have to. 
I'll re-run the Uregni migration this afternoon and we can re-assess then.

**Comment by DuttonMa** [comment]
Actually, ignore that last comment, I think that we should go ahead and merge this now !

(It is not so much the migration of content that we need to worry about, more the fact that we want content editors to use the media entity browser for all attachments when creating future content.)

**Review by DuttonMa — APPROVED** [review]

**Comment by DuttonMa** [comment]
Vacancy change looks good too, please go ahead and merge

**Pull request merged**
