### PR TITLE
D8 un 541

### PR DESCRIPTION
**Pull request by soda736**
We had image and responsive image styles in both the unity install profile and the unity_image_styles module. I have removed all the custom image styles we have in unity_image_styles from the install profile.

### CODE REVIEW

**Review by ooneill547 — COMMENTED** [review]
Just looking at the config files in the unity_image_styles module, I'm not sure if they should have a uuid?

**Comment by soda736** [comment]
I'm not entirely sure, looking through the install profile, some files have uuids and some don't?

**Comment by DuttonMa** [comment]
I'm afraid that I do think that we need to get rid of all of these uuids in config files

**Review by DuttonMa — CHANGES_REQUESTED** [review]
Please remove uuids

**Comment by soda736** [comment]
I've removed all UUIDs from the unity_image_styles module and the unity install profile.

**Review by ooneill547 — APPROVED** [review]

**Review by DuttonMa — APPROVED** [review]

**Pull request merged**
